query Aircraft($tailNumber: String!) {
  aircraft(tailNumber: $tailNumber) {
    id
    iata
    icao
    model
    airlineIata
    description
    tailNumber
    firstFlight
    imageURL
    createdAt
    updatedAt
  }
}

query AircraftPosition($aircraftID: Float!) {
  aircraftPosition(aircraftID: $aircraftID) {
    id
    aircraftID
    latitude
    longitude
    altitude
    flightYear
    flightMonth
    flightDate
    flightNumber
    airlineIata
    originIata
    destinationIata
    createdAt
    updatedAt
  }
}
