query Airport($airportIata: String!) {
  airport(airportIata: $airportIata) {
    id
    name
    iata
    cityName
    cityCode
    timezone
    state
    elevation
    countryCode
    countyName
  }
}

query AirportTsaCheckpointsStatus($dayOfWeek: Float!, $airportIata: String!) {
  airportTsaCheckpointsStatus(
    dayOfWeek: $dayOfWeek
    airportIata: $airportIata
  ) {
    checkpoints {
      checkPointName
      hours {
        hour
        status
      }
    }
    terminalName
  }
}

query AirportTsaWaitTime($airportIata: String!) {
  airportTsaWaitTime(airportIata: $airportIata) {
    dayOfWeek
    hour
    maxWaitMinute
  }
}
