mutation DebugFlightNotification(
  $flightID: String!
  $title: String!
  $body: String!
  $data: JSON
) {
  _sendFlightNotification(
    flightID: $flightID
    title: $title
    body: $body
    data: $data
  )
}
