mutation debugFlightNofication(
  $flightID: String!
  $title: String
  $body: String
  $data: JSON
) {
  debug_sendFlightNotification(
    flightID: $flightID
    title: $title
    body: $body
    data: $data
  )
}
