fragment FullFlightFragment on Flight {
  id
  airlineIata

  airline {
    id
    name
    logoCompactImageURL
  }

  flightNumber

  originTimezone
  originIata
  originTerminal
  originGate

  origin {
    id
    name
    cityName
    countryCode
    iata
  }

  status

  destinationTimezone
  destinationIata
  destinationGate
  destinationTerminal
  destination {
    id
    name
    cityName
    countryCode
    iata
  }

  scheduledGateDeparture
  scheduledGateArrival
  scheduledDuration

  estimatedGateDeparture
  estimatedGateArrival
  estimatedDuration

  actualGateDeparture
  actualGateArrival
  actualDuration
}

query FindFlights(
  $airlineIata: String!
  $flightNumber: String!
  $departureDate: DateTime!
) {
  findFlights(
    airlineIata: $airlineIata
    flightNumber: $flightNumber
    departureDate: $departureDate
  ) {
    ...FullFlightFragment
  }
}

query GetFlightPromptness($airlineIata: String!, $flightNumber: String!) {
  flightPromptness(airlineIata: $airlineIata, flightNumber: $flightNumber) {
    onTimePercent
    rating
    averageDelayTimeMs
  }
}

query GetFlight($flightID: String!) {
  flight(flightID: $flightID) {
    ...FullFlightFragment
  }
}

query GetUserFlights {
  userFlights {
    id
    flightID
    createdAt
    shouldAlert
    flight {
      ...FullFlightFragment
    }
  }
}
