fragment FullFlightFragment on Flight {
  id
  airlineIata

  Airline {
    id
    name
    logoCompactImageURL
  }

  aircraftTailNumber
  flightNumber

  originIata
  originTerminal
  originGate

  Origin {
    id
    name
    cityName
    countryCode
    iata
    timezone
  }

  status

  destinationIata
  destinationGate
  destinationTerminal
  destinationBaggageClaim

  Destination {
    id
    name
    cityName
    countryCode
    iata
    timezone
  }

  scheduledGateDeparture
  scheduledGateArrival

  estimatedGateDeparture
  estimatedGateArrival

  actualGateDeparture
  actualGateArrival
}

query FindFlights(
  $airlineIata: String!
  $flightNumber: String!
  $year: Float!
  $month: Float!
  $date: Float!
) {
  flights(
    airlineIata: $airlineIata
    flightNumber: $flightNumber
    year: $year
    month: $month
    date: $date
  ) {
    ...FullFlightFragment
  }
}

query GetFlightPromptness($flightID: String!) {
  flightPromptness(flightID: $flightID) {
    onTimePercent
    rating
    averageDelayTimeMs
  }
}

query GetFlight($flightID: String!) {
  flight(flightID: $flightID) {
    ...FullFlightFragment
  }
}

query GetRandomFlight {
  randomFlight {
    ...FullFlightFragment
  }
}

query GetUserActiveFlights {
  userActiveFlights {
    id
    flightID
    createdAt
    shouldAlert
    Flight {
      ...FullFlightFragment
    }
  }
}

query GetUserArchivedFlights {
  userArchivedFlights {
    id
    flightID
    createdAt
    Flight {
      ...FullFlightFragment
    }
  }
}
