mutation SyncUser {
  syncUser
}

mutation DeleteUser {
  deleteUser
}

query Preference {
  userPreference {
    measurement
    dateFormat
  }
}

mutation UpdatePreference($data: UpdateUserPreferenceInput!) {
  updateUserPreference(data: $data)
}
