projects:
  default:
    schema: http://localhost:3000/graphql
    documents: "src/graphql/server/*.{graphql,js,ts,jsx,tsx,gql}"
    extensions:
      languageService:
        cacheSchemaFileForLookup: true
  cms:
    schema: https://us-east-1-shared-usea1-02.cdn.hygraph.com/content/clg8hix5b1wdd01uj23zq2ql5/master
    documents: "src/graphql/cms/*.{graphql,js,ts,jsx,tsx,gql}"
    extensions:
      languageService:
        cacheSchemaFileForLookup: true
