projects:
  default:
    schema: http://localhost:3000/graphql
    documents: "src/graphql/server/*.{graphql,js,ts,jsx,tsx,gql}"
    extensions:
      languageService:
        cacheSchemaFileForLookup: true
  cms:
    schema: https://api-us-east-1-shared-usea1-02.hygraph.com/v2/clq5vbkc727ot01um853p7kfo/master
    documents: "src/graphql/cms/*.{graphql,js,ts,jsx,tsx,gql}"
    extensions:
      languageService:
        cacheSchemaFileForLookup: true
