definitions:
  rn_cache: &rn_cache
    cache_paths:
      - $CM_BUILD_DIR/node_modules
      - $HOME/Library/Caches/Yarn
      - $CM_BUILD_DIR/.bundle/packages
  rn_env: &rn_env
    environment:
      vars:
        BUILD_NUMBER: $BUILD_NUMBER
        REPO: $CM_REPO_SLUG
        COMMIT_SHA: $CM_COMMIT
        GOOGLE_APPLICATION_CREDENTIALS: $CM_BUILD_DIR/firebase_credentials.json
  notify_email: &notify_email
    email:
      recipients:
        - apps@flywithavi.com
      notify:
        success: true
        failure: true

  android_cache: &android_cache
    cache_paths:
      - $CM_BUILD_DIR/android/.gradle
      - $CM_BUILD_DIR/android/.idea

  push_trigger: &push_trigger
    cancel_previous_builds: true
    events:
      - push
  scripts:
    - &install_doppler
      name: Import Doppler secrets
      script: |
        brew install gnupg
        brew install dopplerhq/cli/doppler
        doppler secrets download --no-read-env \
          --no-file \
          --format env-no-quotes \
          --config $APP_ENV \
          --token $DOPPLER_TOKEN >> $CM_ENV
    - &make_env_file
      name: Make .env file
      script: |
        node ./scripts/make.env.js
    - &install_bundler
      name: Install bundler
      script: |
        gem install bundler
        bundle install
    - &install_imagemagick
      name: Install imagemagick
      script: |
        brew install imagemagick
    - &install_pod_dep
      name: Pod install
      script: |
        cd ios && pod install
    - &install_rn_dep
      name: Yarn install
      script: |
        yarn --version
        yarn --immutable --immutable-cache --check-cache
    - &mod_google_service_plist
      name: Mod GoogleService-Info.plist
      script: |
        cat ios/GoogleService-Info.${APP_ENV}.plist > ios/GoogleService-Info.plist
    - &create_firebase_credentials
      name: Create Firebase Credentials
      script: |
        echo "$FIREBASE_SERVICE_ACCOUNT" > $GOOGLE_APPLICATION_CREDENTIALS
    - &build_app
      name: Build Application
      script: |
        bundle exec fastlane $LANE

  android_build: &android_build
    <<: [*rn_env]
    name: Android Build
    instance_type: linux_x2
    artifacts:
      - build/android/app/build/outputs/apk/release/*.apk
    publishing:
      <<: *notify_email
    cache:
      <<: [*rn_cache]
      cache_paths:
      - $CM_BUILD_DIR/android/.gradle
      - $CM_BUILD_DIR/android/.idea
    scripts:
      - *install_bundler
      - *install_imagemagick
      - *install_rn_dep
      - *install_doppler
      - *make_env_file
      - *create_firebase_credentials
      - *build_app

  ios_build: &ios_build
    <<: [*rn_env]
    name: iOS Build
    instance_type: mac_mini_m1
    artifacts:
      - build/ios/ipa/*.ipa
      - $CM_BUILD_DIR/ios/*.ipa
      - $CM_BUILD_DIR/ios/*.dSYM.zip
    max_build_duration: 20
    environment:
      xcode: 15.1
      cocoapods: default
      vars:
        SENTRY_DSYM_PATH: $CM_BUILD_DIR/ios/build/Avi.app.dSYM.zip
        GOOGLE_APPLICATION_CREDENTIALS: $CM_BUILD_DIR/firebase_credentials.json
    publishing:
      <<: *notify_email
    cache:
      <<: [*rn_cache]
      cache_paths:
      - $CM_BUILD_DIR/ios/Pods
      - $CM_BUILD_DIR/ios/build/DerivedData
    scripts:
      - *install_bundler
      - *install_imagemagick
      - *install_rn_dep
      - *install_pod_dep
      - *install_doppler
      - *make_env_file
      - *mod_google_service_plist
      - *create_firebase_credentials
      - *build_app

workflows:
  android-staging:
    <<: [*android_build]
    triggering:
      <<: *push_trigger
      branch_patterns:
        - pattern: "staging"
    environment:
      vars:
        APP_ENV: staging
        LANE: android staging

  ios-staging:
    <<: [*ios_build]
    triggering:
      <<: *push_trigger
      branch_patterns:
        - pattern: "staging"
    environment:
      vars:
        APP_ENV: staging
        LANE: ios staging
  ios-beta:
    <<: [*ios_build]
    triggering:
      <<: *push_trigger
      branch_patterns:
        - pattern: "main|beta"
    environment:
      vars:
        APP_ENV: beta
        LANE: ios beta
