# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require "net/http"
fastlane_require "dotenv"

before_all do |lane, options|
  if !is_ci
    UI.message("fastlane load in .env")
    load_remote_env()
  end

  platform = lane_context[SharedValues::PLATFORM_NAME]

  BUILD_SCHEMES  = %i[develop staging].freeze
  AND_GRAD_PATH  = "android/app/build.gradle"
  ICON_IMAGE_LOC =  "app.icon.png"
  AND_PACKAGE_ID = CredentialsManager::AppfileConfig.try_fetch_value(:package_name) || ""
  IOS_IDENTIFIER = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) || ""

  Dir.glob("../ios/*.xcworkspace") do |f|
    UI.message("Found workspace: #{f}")
    IOS_PROJ_NAME = File.basename(f, File.extname(f))
    IOS_DIRECTORY = "ios/#{IOS_PROJ_NAME}"
    IOS_PROJ_PATH = "#{IOS_DIRECTORY}.xcodeproj"
    IOS_WORK_PATH = "#{IOS_DIRECTORY}.xcworkspace"
  end

  if platform == :ios
    lane_context["IOS_SCHEME"]  = add_suffix_to(IOS_PROJ_NAME, lane)
    lane_context["IOS_APP_ID"]  = add_suffix_to(IOS_IDENTIFIER, lane)
    lane_context["PACKAGE_ID"] = lane_context["IOS_APP_ID"]
    UI.message("Setting lane context for iOS... 🏗️")
    UI.message("IOS_SCHEME: #{lane_context["IOS_SCHEME"]}")
    UI.message("IOS_APP_ID: #{lane_context["IOS_APP_ID"]}")
  elsif platform === :android
    lane_context["AND_PACKAGE"] = add_suffix_to(AND_PACKAGE_ID, lane)
    lane_context["PACKAGE_ID"] = lane_context["AND_PACKAGE"]
    UI.message("Setting lane context for Android... 🏗️")
    UI.message("AND_PACKAGE_ID: #{AND_PACKAGE_ID}")
    UI.message("AND_PACKAGE: #{lane_context["AND_PACKAGE"]}")
  end
end

lane :load_remote_env do
  UI.message("Loading remote env from Doppler ... ⏳")
  ensure_env_vars(
    env_vars: [
      "DOPPLER_TOKEN"
    ]
  )

  UI.message("Loading remote .env")
  result = sh("node ../scripts/load.env.js", log: false, print_command: false)
  lines = result.split("\n")
  envKeys = []

  lines.each do |line|
    if (!line.include?("="))
      next
    end

    env_parts = line.split("=")
    key = env_parts[0]
    value = env_parts[1]

    ENV[key] = value
    envKeys << key
  end

  UI.message("Remote env loaded: #{envKeys.join(", ")}")
  UI.message("Loading local .env")
  Dotenv.overload("../.env")
end

lane :liftoff do |options|
  if ENV["FASTLANE_APPLE_DEV_TEAM_ID"].empty? && ENV["FASTLANE_APPLE_ITC_TEAM_ID"].empty?
    UI.message("You haven't set your Apple team IDs, fetching teams now... ⏳")

    client = fetch_teams(true, true)
    dev_team_id = client.portal_client.instance_variable_get(:@current_team_id)
    itc_team_id = client.tunes_client.instance_variable_get(:@current_team_id)

    UI.important("
      If you'd like to skip this prompt in the future\n
      Set the FASTLANE_APPLE_DEV_TEAM_ID environment variable to #{dev_team_id}
      Set the FASTLANE_APPLE_ITC_TEAM_ID environment variable to #{itc_team_id}
    ")
  elsif ENV["FASTLANE_APPLE_DEV_TEAM_ID"].empty?
    UI.message("You haven't set your Apple Developer Team ID, fetching teams now... ⏳")

    client = fetch_teams(true, false)
    the_id = client.portal_client.instance_variable_get(:@current_team_id)

    UI.important("
      If you'd like to skip this prompt in the future\n
      Set the FASTLANE_APPLE_DEV_TEAM_ID environment variable to #{the_id}
    ")
  elsif ENV["FASTLANE_APPLE_ITC_TEAM_ID"].empty?
    UI.message("You haven't set your App Store Connect Team ID, fetching teams now... ⏳")

    client = fetch_teams(false, true)
    the_id = client.tunes_client.instance_variable_get(:@current_team_id)

    UI.important("
      If you'd like to skip this prompt in the future\n
      Set the FASTLANE_APPLE_ITC_TEAM_ID environment variable to #{the_id}
    ")
  end

  UI.message("🚀 Let's GOOOOOOOOOOOO! 🚀")
  generate_metadata

  if UI.confirm("Do you need me to generate Apple bundle identifiers? (yN)")
    generate_apple_identifiers
  end

  if UI.confirm("Do you need me to generate Apple Provisioning Profiles? (yN)")
    generate_apple_profiles
  end

  if UI.confirm("Do you need me to create an app in App Store Connect? (yN)")
    create_app_in_portal
  end

  if UI.confirm("Do you need me to generate an Android keystore for production? (yN)")
    generate_keystore
  end

  UI.success("🎉 All done! 🎉")
end

lane :generate_push_certificate do
  get_push_certificate(
    force: true,
    app_identifier: IOS_IDENTIFIER,
    output_path: 'ios/build'
  )
end

lane :generate_keystore do |options|
  ensure_env_vars(
    env_vars: [
      "FASTLANE_ANDROID_KEYSTORE_ALIAS_NAME",
      "FASTLANE_ANDROID_KEYSTORE_KEYSTORE_NAME"
    ]
  )

  sh("sudo keytool -genkey -v -keystore #{ENV["FASTLANE_ANDROID_KEYSTORE_KEYSTORE_NAME"]} -alias #{ENV["FASTLANE_ANDROID_KEYSTORE_ALIAS_NAME"]} -keyalg RSA -keysize 2048 -validity 10000")
end

lane :update_version do |options|
  increment_version_number(
    xcodeproj: IOS_PROJ_PATH,
    bump_type: options[:type]
  )

  version = get_version_number(
    xcodeproj: IOS_PROJ_PATH
  )

  increment_version_name(
    gradle_file_path: AND_GRAD_PATH,
    version_name: version
  )
end

lane :create_match_profiles do
  IDENTIFIER=ENV['FASTLANE_APPLE_BUNDLE_IDENTIFIER']
  UI.message("Creating match profiles for identifier=#{IDENTIFIER}")

  match(
    type: "development",
    app_identifier: IDENTIFIER + ".develop",
    force: true,
    generate_apple_certs: true,
    skip_provisioning_profiles: false
  )
  match(
    type: "adhoc",
    app_identifier: IDENTIFIER + ".staging",
    force: true,
    generate_apple_certs: true,
    skip_provisioning_profiles: false
  )
  match(
    type: "appstore",
    app_identifier: IDENTIFIER,
    force: true,
    generate_apple_certs: true,
    skip_provisioning_profiles: false
  )
end


lane :copy_assets do |options|
  source = options[:source]
  destination = options[:destination]
  sh("node ../scripts/copy.assets.js --source=#{source} --destination=#{destination}")
end

lane :suffix_name do |options|
  lane = options[:lane]
  ensure_env_vars(
    env_vars: [
      "FASTLANE_PRODUCT_NAME"
    ]
  )

  platform = lane_context[SharedValues::PLATFORM_NAME]
  app_name = ENV["FASTLANE_PRODUCT_NAME"]
  suffix = options[:suffix] ? "(#{options[:suffix]})" : ""
  display_name = "#{app_name} #{suffix}".strip
  UI.message("Display name=#{display_name}")
  update_bundle_identifier(
    platform: platform,
    lane: lane,
    display_name: display_name,
    suffix: options[:suffix]
  )
end

lane :update_bundle_identifier do |options|
  platform = options[:platform].to_sym
  display_name = options[:display_name]

  UI.message("Updating bundle identifier for platform=#{platform}")

  if platform == :ios
    app_identifier = options[:suffix] ? lane_context["IOS_APP_ID"] : "$(PRODUCT_BUNDLE_IDENTIFIER)"
    UI.message("Updating App identifier=#{app_identifier}")
    UI.message("Updating Display Name=#{display_name}")

    update_info_plist(
      xcodeproj: IOS_PROJ_PATH,
      app_identifier: app_identifier,
      plist_path: "/#{IOS_PROJ_NAME}/Info.plist",
      display_name: display_name,
    )
  elsif platform == :android
    bundle_id = lane_context["AND_PACKAGE"]
    UI.message("Updating Bundle ID=#{bundle_id}")
    UI.message("Updating Display Name=#{display_name}")

    update_android_strings(
      block: lambda { |strings|
        strings["app_name"] = display_name
        strings["bundle_id"] = bundle_id
      }
    )
  end
end

lane :prepare_icons do |options|
  platform = options[:platform].to_sym
  lane = options[:lane].to_sym
  UI.message("Generating icons for platform=#{platform} lane=#{lane} at #{ICON_IMAGE_LOC}")

  if platform == :ios
    appicon(
      appicon_image_file: ICON_IMAGE_LOC,
      appicon_path: "#{IOS_DIRECTORY}/Images.xcassets",
      appicon_devices: [:ipad, :iphone, :ios_marketing]
    )
  elsif platform == :android
    android_appicon(
      generate_rounded: true,
      appicon_icon_types: [:launcher],
      appicon_image_file: ICON_IMAGE_LOC,
      appicon_path: "android/app/src/main/res/mipmap"
    )
  end

  if lane != nil and lane != :release
    UI.message("Adding badge for platform=#{platform} lane=#{lane}")
    version = fetch_version(platform)
    shield = "#{version[:name]}-#{version[:code]}-blue"

    if lane == :develop
      shield = "develop-red"
    end

    if platform == :ios
      add_badge(
        shield: shield,
        no_badge: true,
        shield_gravity: "North",
        shield_no_resize: true
      )
      add_badge(
        shield: shield,
        glob: "/ios/**/*/bootsplash_logo*.png",
        no_badge: true,
        shield_gravity: "South",
        shield_no_resize: true
      )
    elsif platform == :android
      add_badge(
        no_badge: true,
        shield: shield,
        glob: "/android/**/*/ic_launcher*.png",
        shield_gravity: "North",
        shield_no_resize: true
      )
      add_badge(
        no_badge: true,
        shield: shield,
        glob: "/android/**/*/bootsplash_logo.png",
        shield_gravity: "South",
        shield_no_resize: true
      )
    end
  end
end

lane :reset do |options|
  platform = options[:platform].to_sym
  files = []

  if platform == :ios
    Dir.glob("../ios/**/*.appiconset") do |file|
      files << File.expand_path(file)
    end
    Dir.glob("../ios/**/*/bootsplash_logo*.png") do |file|
      files << File.expand_path(file)
    end
  elsif platform == :android
    files << File.expand_path("../android/app/src/main/res/values/strings.xml")
    files << File.expand_path("../android/app/src/main/AndroidManifest.xml")

    Dir.glob("../android/**/*/bootsplash_logo.png") do |file|
      files << File.expand_path(file)
    end

    Dir.glob("../android/**/*/ic_launcher*.png") do |file|
      files << File.expand_path(file)
    end
  end

  UI.message("Resetting git repo for platform=#{platform}...")
  UI.message("Files count=#{files.size}")
  reset_git_repo(force: true, files: files)
end

lane :upload_sentry do |options|
  begin
    if !is_ci
      return
    end

    version = fetch_version(:ios)
    commit = get_commit_identifier()
    app_identifier = lane_context["PACKAGE_ID"]

    ensure_env_vars(
      env_vars: [
        "SENTRY_AUTH_TOKEN",
        "SENTRY_ORG_SLUG",
        "SENTRY_PROJECT_SLUG"
      ]
    )

    sentry_set_commits(
      version: version[:name],
      app_identifier: app_identifier,
      build: version[:code],
      auto: false, # enable completely automated commit management
      clear: false, # clear all current commits from the release
      commit: commit, # commit spec, see `sentry-cli releases help set-commits` for more information
      ignore_missing: false # Optional boolean value: When the flag is set and the previous release commit was not found in the repository, will create a release with the default commits count (or the one specified with `--initial-depth`) instead of failing the command.
    )

    sentry_create_deploy(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: ENV['SENTRY_ORG_SLUG'],
      project_slug: ENV['SENTRY_PROJECT_SLUG'],
      version: version[:name],
      app_identifier: app_identifier,
      build: version[:code],
      env: options[:env], # The environment for this deploy. Required.
    )

    sentry_upload_dif(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: ENV['SENTRY_ORG_SLUG'],
      project_slug: ENV['SENTRY_PROJECT_SLUG'],
      include_sources: true,
      finalize: options[:finalize],
    )

    sentry_upload_file(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: ENV['SENTRY_ORG_SLUG'],
      project_slug: ENV['SENTRY_PROJECT_SLUG'],
      version: version[:name],
      app_identifier: app_identifier,
      build: version[:code], # Optionally pass in the build number of your app
      file: 'main.jsbundle' # file to upload
    )
  rescue => ex
    UI.error(ex)
  end
end


platform :ios do
  before_all do
    if is_ci
      setup_circle_ci
    end
  end


  lane :build_application do |options|
    # Disable Metro
    ENV['RCT_NO_LAUNCH_PACKAGER'] = 'true'

    build_app(
      skip_profile_detection: true,
      disable_package_automatic_updates: true,
      silent: false,
      include_symbols: true,
      export_method: options[:export_method],
      include_bitcode: true,
      analyze_build_time: true,
      scheme: options[:scheme],
      workspace: IOS_WORK_PATH,
      output_directory: "ios/build",
      archive_path: "ios/build/app.xcarchive",
      derived_data_path: 'ios/build/DerivedData',
      xcargs: "-allowProvisioningUpdates",
      configuration: options[:configuration],
      export_options: {
        provisioningProfiles: ENV['MATCH_PROVISIONING_PROFILE_MAPPING'],
        # http://docs.fastlane.tools/actions/sync_code_signing/#lane-variables
        signingStyle: "manual"
      }
    )
  end

  lane :fetch_profiles do |options|
    generate_apple_certs = options[:type] == "appstore"
    readonly = is_ci
    type = options[:type]
    identifier = lane_context["IOS_APP_ID"]

    if ENV['MATCH_SSH_KEY'] != nil
      UI.message("Fetching provisioning profiles using ssh with identifier=#{identifier}")
      match(
        type: type,
        readonly: readonly,
        generate_apple_certs: generate_apple_certs,
        app_identifier: identifier,
        git_private_key: Base64.decode64(ENV['MATCH_SSH_KEY']),
      )
    else
      UI.message("Fetching provisioning profiles using github with identifier=#{identifier}")
      ensure_env_vars(
        env_vars: [
          "GITHUB_USERNAME",
          "GITHUB_ACCESS_TOKEN"
        ]
      )
      basic_auth = Base64.strict_encode64(ENV['GITHUB_USERNAME'] + ":" + ENV['GITHUB_ACCESS_TOKEN'])
      match(
        type: type,
        readonly: readonly,
        generate_apple_certs: generate_apple_certs,
        app_identifier: identifier,
        git_basic_authorization: basic_auth,
      )
    end
  end

  desc "Local development using iOS Simulator..."
  lane :develop do |options|
    begin
      scheme = "--scheme #{options[:scheme] || lane_context["IOS_SCHEME"]}"
      device = "--device" if options[:device]
      simulator = "--simulator #{options[:simulator] || '"iPhone 14"'}"

      suffix_name(suffix: "D")
      prepare_icons(platform: :ios, lane: :develop)

      sh('npm', 'run', 'localhost')
      sh "cd .. && npx react-native run-ios #{scheme} #{device ? device : simulator}"
    ensure
      suffix_name(suffix: nil)
      reset(platform: :ios)
    end
  end

  desc "Submit a new staging build to Firebase testers..."
  lane :staging do |options|
    ensure_env_vars(
      env_vars: [
        "FIREBASE_GROUPS",
        "FIREBASE_IOS_APP_ID",
        "FASTLANE_APPLE_USERNAME",
        "FASTLANE_APPLE_BUNDLE_IDENTIFIER",
        "SERVER"
      ]
    )

    begin
      update_code_signing_settings(
        use_automatic_signing: false,
        path: IOS_PROJ_PATH
      )
      increment_build(:ios)
      suffix_name(suffix: "S")
      prepare_icons(platform: :ios, lane: :staging)
      fetch_profiles(type: "adhoc")
      build_application(
        scheme: lane_context["IOS_SCHEME"],
        configuration: "Staging",
        export_method: "ad-hoc"
      )

      firebase_app_distribution(
        app: ENV["FIREBASE_IOS_APP_ID"],
        groups: ENV["FIREBASE_GROUPS"],
        debug: true
      )

      upload_sentry(finalize: false)
      notify_the_team(:ios, :staging)
    ensure
      update_code_signing_settings(
        use_automatic_signing: true,
        path: IOS_PROJ_PATH
      )
      suffix_name(suffix: nil)
      reset(platform: :ios)
    end
  end

  desc "Once staging is approved, submit a production build to TestFlight testers..."
  lane :beta do
    ensure_env_vars(
      env_vars: [
        "APP_STORE_CONNECT_API_KEY_ID",
        "APP_STORE_CONNECT_API_ISSUER_ID",
        "APP_STORE_CONNECT_API_KEY_CONTENT",
        "FASTLANE_APPLE_BUNDLE_IDENTIFIER",
        "FASTLANE_APPLE_USERNAME",
        "FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD",
        "COMMIT_SHA",
        "REPO",
        "SERVER"
      ]
    )

    increment_build(:ios)
    suffix_name(suffix: nil)

    begin
      app_store_connect_api_key(
        key_id: "#{ENV['APP_STORE_CONNECT_API_KEY_ID']}",
        issuer_id: "#{ENV['APP_STORE_CONNECT_API_ISSUER_ID']}",
        key_content: "#{ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]}",
        is_key_content_base64: true
      )

      update_code_signing_settings(
        use_automatic_signing: false,
        path: IOS_PROJ_PATH
      )
      fetch_profiles(type: "appstore")
      build_application(
        scheme: lane_context["IOS_SCHEME"],
        configuration: "Release",
        export_method: "app-store"
      )

      upload_to_testflight(
        skip_waiting_for_build_processing: true,
        reject_build_waiting_for_review: true,
        submit_beta_review: true,
        beta_app_feedback_email: fetch_metadata("review_information/email_address.txt"),
        beta_app_description: fetch_metadata("default/release_notes.txt"),
        demo_account_required: true,
        # changelog: fetch_metadata("default/release_notes.txt"),
        beta_app_review_info: {
          contact_email: fetch_metadata("review_information/email_address.txt"),
          contact_phone: fetch_metadata("review_information/phone_number.txt"),
          contact_first_name: fetch_metadata("review_information/first_name.txt"),
          contact_last_name: fetch_metadata("review_information/last_name.txt"),
          demo_account_name: fetch_metadata("review_information/demo_user.txt"),
          demo_account_password: fetch_metadata("review_information/demo_password.txt"),
          notes: fetch_metadata("review_information/notes.txt")
        },
        localized_app_info: {
          "default": {
            feedback_email: fetch_metadata("review_information/email_address.txt"),
            marketing_url: fetch_metadata("default/marketing_url.txt"),
            privacy_policy_url: fetch_metadata("default/privacy_url.txt"),
            description: fetch_metadata("default/description.txt")
          }
        }
      )

      upload_sentry()
      notify_the_team(:ios, :beta)
      ensure
        update_code_signing_settings(
          use_automatic_signing: true,
          path: IOS_PROJ_PATH
        )
      end
  end

  desc "Once beta is approved, promote beta build to App Store..."
  lane :release do
    get_push_certificate
    upload_to_app_store(
      submission_information: "{\"export_compliance_uses_encryption\": false, \"add_id_info_uses_idfa\": false }",
      skip_screenshots: true,
      include_in_app_purchases: false
    )

    upload_sentry()

    sentry_create_release(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: ENV['SENTRY_ORG_SLUG'],
      project_slug: ENV['SENTRY_PROJECT_SLUG'],
      version: version[:name],
      app_identifier: lane_context["IOS_APP_ID"],
      finalize: true # Whether to finalize the release. If not provided or false, the release can be finalized using the sentry_finalize_release action
    )

    notify_the_team(:ios, :release)
  end
end

platform :android do
  before_all do

    ensure_env_vars(
      env_vars: [
        "GOOGLE_MAP_API_KEY"
      ]
    )
    update_android_strings(
      block: lambda { |strings|
        strings["GOOGLE_MAP_API_KEY"] = ENV['GOOGLE_MAP_API_KEY']
      }
    )
  end

  lane :build_application do |options|
    gradle(
      project_dir: "android",
      flavor: options[:flavor],
      task: "clean #{options[:task] || "bundle"}",
      build_type: options[:build_type] || "release"
    )
  end

  desc "Development..."
  lane :develop do |options|
    appId = "--appIdSuffix=develop"
    variant = "--variant=developDebug"
    device = ""

    if options[:device] != nil
      UI.message("Building for device: #{options[:device]}")
      device = "--deviceId=#{options[:device]}"
    end

    begin
      ensure_env_vars(
        env_vars: [
          "GOOGLE_MAP_API_KEY"
        ]
      )
      update_android_strings(
        block: lambda { |strings|
          strings["GOOGLE_MAP_API_KEY"] = ENV["GOOGLE_MAP_API_KEY"]
        }
      )

      suffix_name(suffix: "D", lane: :develop)
      prepare_icons(platform: :android, lane: :develop)
      sh "yarn localhost"
      sh "cd .. && adb -s #{options[:device]} reverse tcp:8081 tcp:8081 && npx react-native run-android #{device} #{variant} #{appId}"
    ensure
      suffix_name(suffix: nil)
      reset(platform: :android)
    end
  end

  desc "Submit a new staging build to internal testers..."
  lane :staging do
    ensure_env_vars(
      env_vars: [
        "FIREBASE_GROUPS",
        "FIREBASE_AND_APP_ID",
        "FASTLANE_ANDROID_PACKAGE_NAME"
      ]
    )

    increment_build(:android)
    prepare_icons(platform: :android, lane: :staging)
    build_application(flavor: "staging", build_type: "release", task: "assemble")

    # firebase_app_distribution(
    #   android_artifact_type: "APK",
    #   groups: ENV["FIREBASE_GROUPS"],
    #   app: ENV["FIREBASE_AND_APP_ID"],
    #   android_artifact_path: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    # )

    reset(platform: :android)
    notify_the_team(:android, :staging)
  end

  desc "Once staging is approved, submit a production build to beta testers..."
  lane :beta do
    increment_build(:android)
    prepare_icons(platform: :android)
    build_application(flavor: "production")
    upload_to_play_store(track: "beta")
    notify_the_team(:android, :beta)
  end

  desc "Once beta is approved, promote beta build to production..."
  lane :release do
    upload_to_play_store(track: "beta", track_promote_to: "production")
    notify_the_team(:android, :production)
  end
end

def get_commit_identifier()
  repo = ENV['REPO']
  commit_identifier = ENV['COMMIT_SHA']

  if !is_ci
    host = sh("hostname")
    commit_identifier = HOST
  elsif commit_identifier == nil
    commit_identifier = last_git_commit
  end

  commit = repo + '@' + commit_identifier
  return commit
end


def fetch_teams(portal, tunes)
  client = Spaceship::ConnectAPI.login(
    use_portal: portal,
    use_tunes: tunes,
    portal_team_id: nil,
    tunes_team_id: nil,
    team_name: nil,
    skip_select_team: false
  )
end

def generate_metadata
  UI.message("Creating metadata files for easy app creation... ✍🏼")

  Dir.mkdir("metadata") unless Dir.exist?("metadata")
  FileUtils.mkdir_p("metadata/default") unless Dir.exist?("metadata/default")
  FileUtils.mkdir_p("metadata/review_information") unless Dir.exist?("metadata/review_information")

  [
    "copyright.txt",
    "primary_category.txt",
    "secondary_category.txt",
    "primary_first_sub_category.txt",
    "primary_second_sub_category.txt",
    "secondary_first_sub_category.txt",
    "secondary_second_sub_category.txt",
  ].each { |file| FileUtils.touch("metadata/#{file}") }

  [
    "name.txt",
    "subtitle.txt",
    "privacy_url.txt",
    "apple_tv_privacy_policy.txt",
    "description.txt",
    "keywords.txt",
    "release_notes.txt",
    "support_url.txt",
    "marketing_url.txt",
    "promotional_text.txt"
  ].each { |file| FileUtils.touch("metadata/default/#{file}") }

  [
    "first_name.txt",
    "last_name.txt",
    "email_address.txt",
    "phone_number.txt",
    "demo_user.txt",
    "demo_password.txt",
    "notes.txt"
  ].each { |file| FileUtils.touch("metadata/review_information/#{file}") }
end

def generate_apple_identifiers
  id = Spaceship::ConnectAPI::BundleId.create(
    name: IOS_PROJ_NAME,
    identifier: IOS_IDENTIFIER,
  )

  UI.success("Created main bundle identifier... #{IOS_IDENTIFIER} ✅")

  id.create_capability(Spaceship::ConnectAPI::BundleIdCapability::Type::PUSH_NOTIFICATIONS)

  UI.success("Added push notifications as a capability... ✅")

  BUILD_SCHEMES.each do |schema|
    id = Spaceship::ConnectAPI::BundleId.create(
      identifier: "#{IOS_IDENTIFIER}.#{schema}",
      name: "#{IOS_PROJ_NAME.capitalize} #{schema.capitalize}"
    )

    UI.success("Created #{scheme} bundle identifier... #{IOS_IDENTIFIER}.#{schema} ✅")

    id.create_capability(Spaceship::ConnectAPI::BundleIdCapability::Type::PUSH_NOTIFICATIONS)
  end

  generate_push_certificate

  UI.success("Apple identifiers created successfully... 🏁")
end

def generate_apple_profiles
  match(
    app_identifier: [IOS_IDENTIFIER] + BUILD_SCHEMES.map {|schema| "#{IOS_IDENTIFIER}.#{schema}"}
  )

  UI.success("Apple provisioning profiles created successfully... 🏁")
end

def create_app_in_portal
  sku = prompt(
    text: "What is the SKU for this app?"
  )

  produce(
    app_name: ENV["FASTLANE_PRODUCT_NAME"],
    language: "English",
    app_version: "1.0.0",
    sku: sku
  )
end

def fetch_version(platform)
  if platform == :ios
    {
      name: get_version_number(xcodeproj: IOS_PROJ_PATH, target: 'Avi'),
      code: get_build_number(xcodeproj: IOS_PROJ_PATH)
    }
  elsif platform == :android
    {
      name: android_get_version_name(gradle_file: AND_GRAD_PATH),
      code: android_get_version_code(gradle_file: AND_GRAD_PATH)
    }
  end
end

def increment_build(platform)
  # https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/blob/master/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_get_latest_release.rb
  # https://circleci.com/docs/deploy-ios-applications/
  if platform == :ios
    curr_build_number = 0
    if ENV["BUILD_NUMBER"]
      curr_build_number = ENV["BUILD_NUMBER"]
    else
      prev_build_number = latest_testflight_build_number
      curr_build_number = prev_build_number + 1
    end

    increment_build_number(
      xcodeproj: IOS_PROJ_PATH,
      build_number: curr_build_number
    )
  elsif platform == :android
    ensure_env_vars(
      env_vars: [
        "FIREBASE_AND_APP_ID",
      ]
    )

    firebase_app_id = ENV["FIREBASE_AND_APP_ID"]
    latest_release = firebase_app_distribution_get_latest_release(
      debug: !is_ci,
      app: firebase_app_id
    )

    prev_build_number = latest_release ? latest_release[:buildVersion]&.to_i : 0
    curr_build_number = prev_build_number + 1

    increment_version_code(
      gradle_file_path: AND_GRAD_PATH,
      version_code: curr_build_number
    )
  end
end

def notify_the_team(platform, lane)
  # ensure_env_vars(
  #   env_vars: [
  #     "FASTLANE_SLACK_CHANNEL",
  #     "FASTLANE_SLACK_WEBHOOK_URL"
  #   ]
  # )

  # version = fetch_version(platform)
  # message = platform == :ios \
  #   ? "Check TestFlight for new version..." \
  #   : "https://play.google.com/store/apps/details?id=#{lane_context["PACKAGE_NAME"]}"

  # instructions = %i[staging internal].include?(lane) ? "Lookout for Firebase email..." : message

  # slack(
  #   message: "#{instructions}\n\n",
  #   channel: "##{ENV["FASTLANE_SLACK_CHANNEL"]}",
  #   slack_url: ENV["FASTLANE_SLACK_WEBHOOK_URL"],
  #   use_webhook_configured_username_and_icon: false,
  #   pretext: "#{ENV["FASTLANE_PRODUCT_NAME"]} #{platform} Build: #{lane} #{version[:name]} (#{version[:code]})"
  # )
end

def add_suffix_to(value, lane)
  value += ".#{lane}" if BUILD_SCHEMES.include?(lane)
  value
end

def fetch_metadata(key)
  File.read("metadata/#{key}")
end
