fragment LegalFragment on Legal {
  title
  publishedAt
  content {
    markdown
  }
}

query PrivacyPolicy {
  legal(where: { id: "clg9gskh61n190bl9i3bfmn9q" }) {
    ...LegalFragment
  }
}

query TermsAndConditions {
  legal(where: { id: "clg9gtz9g1mp30bk6lfmg9g0x" }) {
    ...LegalFragment
  }
}
